client:
  impl: api
dir_rule:
  base_dir: data/jmDownload
  rule: Bd_Aid_Pindex
download:
  cache: true
  image:
    decode: true
    suffix: .jpg
  threading:
    image: 30
log: true
plugins:
  after_init:
  - kwargs:
      whitelist:
      - api
      - html
    plugin: log_topic_filter
version: '2.0'
